### ISSUE TITLE
Can't display audio transcription on real iPhone!

### ISSUE THREAD

**Issue by yoinspiration** [ClearCut3000/SpeechToDo#1]
ForEach<Array<Float>, Float, VisualBarView>: the ID 0.0 occurs multiple times within the collection, this will give undefined results!

SpeechToDo[13885:982227] [as_client]     AVAudioSession_iOS.mm:2382  Failed to set category, error: -50
There was a problem starting recording: The operation couldn’t be completed. (OSStatus error -50.)

ForEach<Array<Float>, Float, VisualBarView>: the ID -69.56385 occurs multiple times within the collection, this will give undefined results!

**Comment by ClearCut3000** [comment]
The error "ForEach<Array, Float, VisualBarView>: the ID occurs multiple times within the collection, this will give undefined results!" is caused when using the same ID for multiple items in a `ForEach` loop. Each item in a `ForEach` loop must have a unique ID, otherwise it will cause unexpected behavior.

The error "AVAudioSession_iOS.mm:2382 Failed to set category, error: -50 There was a problem starting recording: The operation couldn’t be completed. (OSStatus error -50.)" is caused by a problem with the audio session category. The error code -50 indicates an invalid parameter, which could mean that the audio session category was not set correctly. This can happen if the app doesn't have permission to use the microphone, or if the audio session is already in use by another app.

To fix these errors, ensure that each item in the `ForEach` loop has a unique ID, and check that your app has permission to use the microphone and that the audio session category is set correctly.
